### PR TITLE
Three-word component names

### PR DESCRIPTION
**Pull request by ricotheque**
I would like to make the rule on naming components a bit more clear.

### CODE REVIEW

**Comment by mzdr** [comment]
Hey @rstacruz, what do you think about that? I actually think it's fine.

**Comment by rstacruz** [comment]
Sorry dude, I *swear* i thought I merged this last year!

**Comment by rstacruz** [comment]
I'd say `rico-custom-header` could be a better example though, but I can't think of any better right now. As nice as it is, I don't think people would really use their names in class names in a real-world scenario :)

**Comment by ricotheque** [comment]
You're right. I guess I was too enthralled by our common nicknames. 😝 

Would something `.article-card-wrap` or `.feed-article-wrap` work better?

**Pull request merged**
