### PR TITLE
Add translations

### PR DESCRIPTION
**Pull request by rstacruz**
Here are some translations of RSCSS. Let me know if there are any others!

I'd like to reach out to their respective authors before merging this in.

### CODE REVIEW

**Comment by rstacruz** [comment]
There are some people explaining it in different languages, too. Might be worth linking them as well:
- https://www.youtube.com/watch?v=oI55da0kONc (Russian)
- https://willianjusten.com.br/falando-sobre-rscss/ (Portuguese)

**Comment by mrmlnc** [comment]
@rstacruz, video on the Russian language is almost impossible to listen. I can translate the documentation into Russian language and provide a link.

**Comment by rstacruz** [comment]
Haha, feel free to do so! Lemme know how I can help.

**Comment by ghost** [comment]
I can create a Spanish translation, if that sounds good to you let me know!

**Comment by rstacruz** [comment]
Yes, by all means!

**Comment by ghost** [comment]
Cool, I can start with that now, is there anything I should take on consideration or can I just translate the text in a forked repo?

**Comment by rstacruz** [comment]
Yes that's the easiest way. :)

**Comment by ghost** [comment]
Okay, here it is (going to be): https://github.com/jameskolce/rscss-es

**Comment by rstacruz** [comment]
Okay, got all the go signals, let's do this

**Pull request merged**
